### ISSUE TITLE
A user must be inside the intranet to edit the calendar

### ISSUE THREAD

**Issue by osteele** [olinlibrary/ABE#103]
This issue was originally “Implement access control for items that modify the calendar”. The first phase of access control is to restrict API access entirely. I've repurposed this issue to represent that requirement.

**Comment by osteele** [comment]
Branch [intranet-auth](/github/linguist/ABE/intranet-auth) implements this. It's not yet a PR because it hasn't been tested with the front end. It's waiting in the wings in case we need it in a hurry, or to schedule the remaining work into the project.

**Comment by newsch** [comment]
Thanks for starting this @osteele!

**Comment by osteele** [comment]
The former `intranet-auth` branch is merged, but the environment variable hasn't been set on any of the apps. Remaining work is listed in the comment above.

**Comment by osteele** [comment]
Remaining work is to verify that there's test coverage for the API protection.

**Comment by osteele** [comment]
This event now only represents modifications (updates and deletion). The “view…the calendar” part has moved to #211.
