### ISSUE TITLE
All-day events take up two days in ICS feed

### ISSUE THREAD

**Issue by kylecombes** [olinlibrary/ABE#108]
Event:
![image](https://user-images.githubusercontent.com/3915596/30249299-a8ff414e-9607-11e7-8d2d-b5bc407eecd5.png)

Subscribed calendar:
![image](https://user-images.githubusercontent.com/3915596/30249306-d7dcd530-9607-11e7-9296-5a1d4ef76669.png)

@audreywl may have more details

**Comment by audreywl** [comment]
This may also have some overlap with the bug causing some (but not all) events to shift forward a minute on certain subscribed calendars:
![abe long one-day example 2](https://user-images.githubusercontent.com/16826107/30344681-4d3fe550-97d0-11e7-8487-10a69cd8029d.PNG)

**Comment by audreywl** [comment]
Dug deeper into this issue, which is primarily caused by errors with event creation on the frontend. We need to somehow fix the events already in ABE, though, and set all the seconds for all times to 00.

**Comment by newsch** [comment]
@audreywl that's definitely doable, once you have a better idea of what needs to be changed we can modify the db.

**Comment by audreywl** [comment]
So is it not a rounding error? Or is it just that it's us rounding before we send the iCal? Because I saw pretty consistent behavior of anything with >30 seconds rounding to the next minute.

**Comment by kylecombes** [comment]
If it is a rounding error, I think it should be handled on the backend.

**Comment by newsch** [comment]
_Steps:_
- [ ] remove seconds from incoming events
- [ ] remove seconds from events in db

**Comment by mpbrucker** [comment]
After doing a bit of digging, this issue appears to stem from [this line](https://github.com/olinlibrary/ABE/blob/dde1e326ce8f6f60a27861dd756abb07cd1cf0c8/abe/helper_functions/ics_helpers.py#L58):
```
event_end = str(int(event_end) + 1)
```
which is for some reason converting the end date from a string to an int, incrementing it, and converting back to a string. This appears to be a remnant of some [code](https://github.com/olinlibrary/ABE/commit/1a15c8508303baf7d266a802d9b1303fb03932c3#diff-f388dfa4c1a4e0d9e1136884673e8170L45) that appeared to correct the end dates for all-day events that didn't actually have a duration of one day. Removing this line gives:
```
BEGIN:VEVENT
SUMMARY:Olin Monday
UID:5978c6587412b80011ab8225
DESCRIPTION:Monday class schedule in effect for Olin\n\nNormal Friday sche
 dule for Babson and Wellesley classes
DTEND;VALUE=DATE:20170930
DTSTART;VALUE=DATE:20170929
LOCATION:None
TRANSP:OPAQUE
END:VEVENT
```
which appears to be correct. Another thing of note: this format of `DTEND` and `DTSTART` works for all-day events, but another avenue that could potentially be explored for single-day all-day events is to simply omit `DTEND`, which creates a single-day event as per [RFC5545](https://tools.ietf.org/html/rfc5545#page-54).

**Comment by kylecombes** [comment]
Omitting `DTEND` shouldn't break anything on the frontend. I'd vote for that route.

**Comment by mpbrucker** [comment]
Made a [new branch](https://github.com/olinlibrary/ABE/tree/mpbrucker/all-day-ical-fix) to implement a simple fix - basically, now if an event is an all-day event that's less than a day in duration, it just omits the end date. Everything seems to work in the quick tests I did - a single-day event appears as:
```
BEGIN:VEVENT
SUMMARY:Olin Monday
UID:5978c6587412b80011ab8225
DESCRIPTION:Monday class schedule in effect for Olin\n\nNormal Friday sche
 dule for Babson and Wellesley classes
DTSTART;VALUE=DATE:20170929
LOCATION:None
TRANSP:OPAQUE
END:VEVENT
```
This event also appears normal when imported as an iCal. And multi-day all-day events still appear as:
```
BEGIN:VEVENT
SUMMARY:Spring Break
UID:5a760c64e8fb6d000a5fc366
DESCRIPTION:No Olin Classes
DTEND;VALUE=DATE:20180324
DTSTART;VALUE=DATE:20180319
LOCATION:None
TRANSP:OPAQUE
END:VEVENT
```
