### ISSUE TITLE
Fix order of outputted data

### ISSUE THREAD

**Issue by newsch** [olinlibrary/ABE#109]
Currently JSON fields are not ordered. Options include using OrderedDict or python 3.6 (where all dictionaries are ordered).

**Comment by osteele** [comment]
Requiring Python 3.6 sounds like a winner. If #120 implements the switch to pipenv, this can be specified in the `Pipfile`, where Heroku and local pipenv environments will both pick it up.

**Comment by osteele** [comment]
The Pipfile now specifies Python 3.6.
