### ISSUE TITLE
Generate a long-term backup solution

### ISSUE THREAD

**Issue by newsch** [olinlibrary/ABE#114]

**Comment by osteele** [comment]
Backups run nightly on production. Access is documented [here](https://docs.google.com/document/d/1FHuggpiLBcxsvAP2gk70Jl9WFbOwz8U1yMuy3NQTDYI/edit#).

Remaining work is to test recovery, and document the process.

**Comment by osteele** [comment]
Tested recovery; added docs [here](https://docs.google.com/document/d/1FHuggpiLBcxsvAP2gk70Jl9WFbOwz8U1yMuy3NQTDYI/edit#).
