### ISSUE TITLE
PUT requests return old data

### ISSUE THREAD

**Issue by audreywl** [olinlibrary/ABE#46]
For example: if I update the location in an event, the response to my PUT request has the old data in the location field.

**Comment by newsch** [comment]
I'm guessing this is related to not reloading the mongoengine object when calling `update()`

**Comment by newsch** [comment]
It looks like we'll need to call `reload()` after updating the document as explained in [MongoEngine's atomic updates section](https://mongoengine.readthedocs.io/en/latest/guide/querying.html?highlight=querying#atomic-updates).
