### ISSUE TITLE
An unauthenticated client should not receive non-public events

### ISSUE THREAD

**Issue by audreywl** [olinlibrary/ABE#75]
For Olin IP addresses, send back events with 'public' and 'olin' visibility. For all other, send back just 'public'

Depending on the order of tasks, it may be expedient to skip this and go straight to #216.

**Comment by newsch** [comment]
This could be done by checking the headers of the request:
https://stackoverflow.com/questions/22868900/how-do-i-safely-get-the-users-real-ip-address-in-flask-using-mod-wsgi

**Comment by osteele** [comment]
@songbird175 I don't know if we still want this approach, but if we do this at all, it looks related to the are you're working on.
